# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paso',
            options={'verbose_name_plural': 'Pasos'},
        ),
        migrations.RemoveField(
            model_name='receta',
            name='pasos',
        ),
        migrations.AddField(
            model_name='receta',
            name='pasos',
            field=models.ManyToManyField(help_text='Pasos para realizar la receta', to='recetas.Paso', verbose_name='Pasos de la receta'),
        ),
    ]
