# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_auto_20170814_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso',
            name='referencia',
            field=models.CharField(default='', help_text='Referencia para ubicar el paso facilmente', max_length=40),
            preserve_default=False,
        ),
    ]
