# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_paso_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso',
            name='paso',
            field=models.TextField(help_text='Pasos para realizar la receta', verbose_name='Preparaci\xf3n'),
        ),
    ]
