# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20170815_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('version', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Versiones',
            },
        ),
    ]
