# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_auto_20170905_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interaction',
            new_name='Interaccion',
        ),
    ]
