# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_auto_20170905_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaccion',
            options={'verbose_name_plural': 'Interacciones'},
        ),
        migrations.AddField(
            model_name='interaccion',
            name='usuario_id',
            field=models.PositiveSmallIntegerField(default=1, help_text='Id de usuario que interactua'),
            preserve_default=False,
        ),
    ]
