# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_auto_20170905_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.PositiveSmallIntegerField(help_text='Id de usuario que interactua')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='recetas.Receta')),
            ],
            options={
                'verbose_name_plural': 'Compartidos',
            },
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.PositiveSmallIntegerField(help_text='Id de usuario que interactua')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas', to='recetas.Receta')),
            ],
            options={
                'verbose_name_plural': 'Me gustas',
            },
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='receta',
        ),
        migrations.DeleteModel(
            name='Interaccion',
        ),
    ]
