# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_auto_20170905_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='megusta',
            options={'ordering': ['receta'], 'verbose_name_plural': 'Me gustas'},
        ),
        migrations.AlterUniqueTogether(
            name='megusta',
            unique_together=set([('receta', 'usuario_id')]),
        ),
    ]
