# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recetas', '0011_auto_20170905_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compartido',
            options={'ordering': ['receta', 'usuario_id'], 'verbose_name_plural': 'Compartidos'},
        ),
        migrations.AlterModelOptions(
            name='megusta',
            options={'ordering': ['receta', 'usuario_id'], 'verbose_name_plural': 'Me gustas'},
        ),
        migrations.AddField(
            model_name='megusta',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_gustas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='compartido',
            unique_together=set([('receta', 'usuario_id')]),
        ),
    ]
