# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_auto_20170905_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megusta',
            name='owner',
        ),
    ]
