# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_remove_megusta_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compartido',
            unique_together=set([]),
        ),
    ]
