# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_auto_20170905_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterField(
            model_name='compartido',
            name='usuario_id',
            field=models.IntegerField(help_text='Id de usuario que interactua'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='recetas.Unidad'),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='usuario_id',
            field=models.IntegerField(help_text='Id de usuario que interactua'),
        ),
    ]
