# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0015_auto_20170912_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(max_length=80),
        ),
    ]
