# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0017_auto_20170912_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado del ingrediente para la receta (Ej. Cocido, rallado, picado finamente, etc)', max_length=200, null=True),
        ),
    ]
